# Generated by Django 4.0.4 on 2022-05-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(default='1', max_length=100, primary_key=True, serialize=False)),
                ('slackuser_id', models.CharField(max_length=100)),
                ('text', models.CharField(default='', max_length=300)),
                ('file', models.CharField(default='', max_length=300)),
                ('timestamp', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('slackuser_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
