# Generated by Django 4.0.4 on 2022-05-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackmessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='1', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='slackuser_id',
            field=models.CharField(max_length=300),
        ),
    ]
