version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Install `docker-compose`
          command: |
            curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
            pip install docker-compose docker==2.3
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Running tests
          command: |
            docker-compose up django-test --build --abort-on-container-exit --exit-code-from django-test
      - store_artifacts:
          path: test-reports/
          destination: slack_integration_app
